# DEV - commnet local and uncomment this for dev
@base_url=http://localhost:3002/simplebank

### Create a new account
POST {{base_url}}/accounts HTTP/1.1
Content-Type: application/json

{
  "owner": "Alice",
  "balance": 1000,
  "currency": "USD"
}

### Get account by id
GET {{base_url}}/accounts/1 HTTP/1.1

### List accounts
GET {{base_url}}/accounts HTTP/1.1

### Delete account by id
DELETE {{base_url}}/accounts/1 HTTP/1.1

### Create a new transfer
POST {{base_url}}/accounts/transfers HTTP/1.1
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2,
  "amount": 500
}